name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, xml, gd
          ini-values: post_max_size=256M, memory_limit=1G

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Install composer
        uses: php-actions/composer@v6

      - name: Install PHP dependencies
        run: composer install --no-progress --no-suggest --prefer-dist -q

      - name: Prepare environment
        run: cp .env.example .env || true

      - name: Generate APP_KEY
        run: php artisan key:generate --ansi || true

      - name: Run migrations
        run: php artisan migrate --force || true

      - name: Run tests
        run: vendor/bin/phpunit --configuration phpunit.xml --colors=always
